package com.shadt.iptv_qx.utils;

public class StringsLife2 {
    public static String data="{\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"viewid\":\"logo\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"1\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtOut\",\n" +
            "                \"width\":470,\n" +
            "                \"height\":45,\n" +
            "                \"x\":120,\n" +
            "                \"y\":70\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"text\",\n" +
            "            \"content\":{\n" +
            "                \"title\":\"教育服务\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"width\":380,\n" +
            "                \"height\":120,\n" +
            "                \"x\":1450,\n" +
            "                \"y\":45,\n" +
            "                \"fontsize\":36,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"news\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"11\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"教育资助政策\",\n" +
            "                \"interface\":\"http://fjyx.chinashadt.com//Interface/Recodrd/listRecod1.do?key=YXXWWYXNEWS\",\n" +
            "                \"pageNum\":2,\n" +
            "                \"getSize\":10,\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"listSmImgL\",\n" +
            "                \"width\":480,\n" +
            "                \"height\":720,\n" +
            "                \"x\":120,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"refreshtime\":5000,\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"openvisualization\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&amp;quality=100&amp;size=b4000_4000&amp;sec=1598251131&amp;di=54b500f8798f80fb2f176b24834171b2&amp;src=http://a3.att.hudong.com/14/75/01300000164186121366756803686.jpg\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"幼儿园查询及报名咨询\",\n" +
            "                \"interface\":\"\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":580,\n" +
            "                \"height\":350,\n" +
            "                \"x\":620,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&amp;quality=100&amp;size=b4000_4000&amp;sec=1598251131&amp;di=54b500f8798f80fb2f176b24834171b2&amp;src=http://a3.att.hudong.com/14/75/01300000164186121366756803686.jpg\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"中小学教育\",\n" +
            "                \"interface\":\"请求接口\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":580,\n" +
            "                \"height\":350,\n" +
            "                \"x\":1220,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&amp;quality=100&amp;size=b4000_4000&amp;sec=1598251131&amp;di=54b500f8798f80fb2f176b24834171b2&amp;src=http://a3.att.hudong.com/14/75/01300000164186121366756803686.jpg\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"中考信息\",\n" +
            "                \"interface\":\"请求接口\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":580,\n" +
            "                \"height\":350,\n" +
            "                \"x\":620,\n" +
            "                \"y\":564,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&amp;quality=100&amp;size=b4000_4000&amp;sec=1598251131&amp;di=54b500f8798f80fb2f176b24834171b2&amp;src=http://a3.att.hudong.com/14/75/01300000164186121366756803686.jpg\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"职业教育培训\",\n" +
            "                \"interface\":\"请求接口\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":280,\n" +
            "                \"height\":350,\n" +
            "                \"x\":1220,\n" +
            "                \"y\":564,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"1\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"成人考试服务\",\n" +
            "                \"interface\":\"请求接口\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":280,\n" +
            "                \"height\":350,\n" +
            "                \"x\":1520,\n" +
            "                \"y\":564,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        }\n" +
            "    ],\n" +
            "    \"code\":200,\n" +
            "    \"msg\":\"请求成功\"\n" +
            "}";


}
