package com.shadt.iptv_qx.utils;

public class Stringwenmingshijian {
    public static String data="{\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"viewid\":\"logo\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"logo_top.png\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtOut\",\n" +
            "                \"width\":470,\n" +
            "                \"height\":45,\n" +
            "                \"x\":120,\n" +
            "                \"y\":70\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"news\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"11\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"实践动态\",\n" +
            "                \"interface\":\"OHPGCQPCTVPQRCSO\",\n" +
            "                \"pageNum\":2,\n" +
            "                \"getSize\":10,\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"listSmImgL\",\n" +
            "                \"width\":480,\n" +
            "                \"height\":720,\n" +
            "                \"x\":120,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"refreshtime\":5000,\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_shijianzhendi.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"实践阵地\",\n" +
            "                \"interface\":\"TSLEFETLQVLIGXXL\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":445,\n" +
            "                \"height\":720,\n" +
            "                \"x\":620,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_shijianhuodong.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"实践活动\",\n" +
            "                \"interface\":\"ECDLXVNSAMLYZHFN\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":445,\n" +
            "                \"height\":350,\n" +
            "                \"x\":1085,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_xuexiyuandi.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"学习园地\",\n" +
            "                \"interface\":\"BQVHYHUAEAXTPHKO\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":445,\n" +
            "                \"height\":350,\n" +
            "                \"x\":1085,\n" +
            "                \"y\":564,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_yingyin.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"文明影音\",\n" +
            "                \"interface\":\"UTGIRMPFSPKWVHVB\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":250,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1550,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_xianjin.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"先进典型\",\n" +
            "                \"interface\":\"XVSQSBOKOQWBIIFC\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":250,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1550,\n" +
            "                \"y\":440,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_zhiyuanfuwu.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"志愿服务\",\n" +
            "                \"interface\":\"SEOQSQVUWTLHIOAY\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":250,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1550,\n" +
            "                \"y\":686,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "       {\n" +
            "            \"viewid\":\"scrolltext\",\n" +
            "             \n" +
            "            \"content\":{\n" +
            "                \"title\":\"欢迎来到可视化平台\"\n" +
            "                 \n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"leftright\",\n" +
            "                \"width\":1920,\n" +
            "                \"height\":45,\n" +
            "                \"x\":0,\n" +
            "                \"y\":970,\n" +
            "\"fontsize\":36,\n" +
            "\"fontcolor\":\"#ffffff\"\n" +
            "              \n" +
            "            }\n" +
            "        }, {\n" +
            "            \"viewid\":\"text\",\n" +
            "            \"content\":{\n" +
            "                \"title\":\"文明实践\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"width\":200,\n" +
            "                \"height\":120,\n" +
            "                \"x\":1600,\n" +
            "                \"y\":45,\n" +
            "                \"fontsize\":36,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        }\n" +
            "    ],\n" +
            "    \"code\":200,\n" +
            "    \"msg\":\"请求成功\"\n" +
            "}";
}
