package com.shadt.iptv_qx.utils;

public class StringeYiliao {
    public static String data="{\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"viewid\":\"logo\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"logo_top.png\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtOut\",\n" +
            "                \"width\":470,\n" +
            "                \"height\":45,\n" +
            "                \"x\":120,\n" +
            "                \"y\":70\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"text\",\n" +
            "            \"content\":{\n" +
            "                \"title\":\"医疗卫生\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"width\":200,\n" +
            "                \"height\":120,\n" +
            "                \"x\":1600,\n" +
            "                \"y\":45,\n" +
            "                \"fontsize\":36,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"news\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"11\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"健康资讯\",\n" +
            "                \"interface\":\"UEZNFPXJWLPUFBEK\",\n" +
            "                \"pageNum\":2,\n" +
            "                \"getSize\":10,\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"listSmImgL\",\n" +
            "                \"width\":480,\n" +
            "                \"height\":720,\n" +
            "                \"x\":120,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"refreshtime\":5000,\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image20.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"预约挂号\",\n" +
            "                \"interface\":\"GRAHMQUOOVNOMERC\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":930,\n" +
            "                \"height\":474,\n" +
            "                \"x\":620,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image15.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"医保药品目录\",\n" +
            "                \"interface\":\"LLMYGHAZXYNKYCWJ\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":230,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1570,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image21.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"诊疗项目目录\",\n" +
            "                \"interface\":\"XCEMGMFJVFHMWNSY\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":230,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1570,\n" +
            "                \"y\":440,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image5.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"服务设施目录\",\n" +
            "                \"interface\":\"RGQVSFTFJVSSWABH\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":230,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1570,\n" +
            "                \"y\":686,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":false\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image17.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"医疗机构查询\",\n" +
            "                \"interface\":\"SCDJSRTTHOUQPJYX\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":296,\n" +
            "                \"height\":226,\n" +
            "                \"x\":620,\n" +
            "                \"y\":686,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image16.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"医保政策解读\",\n" +
            "                \"interface\":\"FVHQEVPBRCQAJFCV\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":296,\n" +
            "                \"height\":226,\n" +
            "                \"x\":936,\n" +
            "                \"y\":686,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"scrolltext\",\n" +
            "             \n" +
            "            \"content\":{\n" +
            "                \"title\":\"欢迎来到可视化平台\"\n" +
            "                 \n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"leftright\",\n" +
            "                \"width\":1920,\n" +
            "                \"height\":45,\n" +
            "                \"x\":0,\n" +
            "                \"y\":970,\n" +
            "\"fontsize\":36,\n" +
            "\"fontcolor\":\"#ffffff\"\n" +
            "              \n" +
            "            }\n" +
            "        },{\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image18.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"疫苗接种\",\n" +
            "                \"interface\":\"ARVQPRDJNXKXIHYV\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":296,\n" +
            "                \"height\":226,\n" +
            "                \"x\":1252,\n" +
            "                \"y\":686,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        }\n" +
            "    ],\n" +
            "    \"code\":200,\n" +
            "    \"msg\":\"请求成功\"\n" +
            "}";
}
