package com.shadt.iptv_qx.utils;

public class StringeDangjian {
    public static String data="{\n" +
            "    \"data\":[\n" +
            "         {\n" +
            "            \"viewid\":\"logo\",\n" +
            "             \n" +
            "            \"content\":{\n" +
            "                \"img\":\"logo_top.png\"\n" +
            "                 \n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtOut\",\n" +
            "                \"width\":470,\n" +
            "                \"height\":45,\n" +
            "                \"x\":120,\n" +
            "                \"y\":70\n" +
            "              \n" +
            "            }\n" +
            "        },\n" +
            "        \n" +
            "        {\n" +
            "            \"viewid\":\"news\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"11\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"党建要闻\",\n" +
            "                \"interface\":\"ZACHXWPTBNQZMVXL\",\n" +
            "                \"pageNum\":2,\n" +
            "                \"getSize\":10,\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"listSmImgL\",\n" +
            "                \"width\":480,\n" +
            "                \"height\":720,\n" +
            "                \"x\":120,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"refreshtime\":5000,\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image11.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"精品党课\",\n" +
            "                \"interface\":\"FYGATAJKVFURPGGK\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":580,\n" +
            "                \"height\":430,\n" +
            "                \"x\":620,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image22.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"直播讲堂\",\n" +
            "                \"interface\":\"SIQSJYPSYMGHLXUC\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":580,\n" +
            "                \"height\":430,\n" +
            "                \"x\":1220,\n" +
            "                \"y\":194,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image8.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"基层党建\",\n" +
            "                \"interface\":\"IXNJTLKPTUEJWHEO\t\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":270,\n" +
            "                \"x\":620,\n" +
            "                \"y\":644,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image7.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"红色影视\",\n" +
            "                \"interface\":\"VCWZFHTFYGGNHTGV\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":270,\n" +
            "                \"x\":1020,\n" +
            "                \"y\":644,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image3.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"党员风采\",\n" +
            "                \"interface\":\"QRWPLLKOQUTTXCCR\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":270,\n" +
            "                \"x\":1420,\n" +
            "                \"y\":644,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        }, {\n" +
            "            \"viewid\":\"scrolltext\",\n" +
            "             \n" +
            "            \"content\":{\n" +
            "                \"title\":\"欢迎来到可视化平台\"\n" +
            "                 \n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"leftright\",\n" +
            "                \"width\":1920,\n" +
            "                \"height\":45,\n" +
            "                \"fontsize\":36,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"x\":0,\n" +
            "                \"y\":970\n" +
            "              \n" +
            "            }\n" +
            "        },{\n" +
            "            \"viewid\":\"text\",\n" +
            "         \n" +
            "            \"content\":{\n" +
            "                 \n" +
            "                \"title\":\"党员服务\"\n" +
            "                \n" +
            "            },\n" +
            "            \"style\":{\n" +
            "              \n" +
            "                \"width\":200,\n" +
            "                \"height\":120,\n" +
            "                \"x\":1600,\n" +
            "                \"y\":45,\n" +
            "              \n" +
            "                \"fontsize\":36,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        }\n" +
            "    ],\n" +
            "    \"code\":200,\n" +
            "    \"msg\":\"请求成功\"\n" +
            "}";
}
