package com.shadt.iptv_qx.utils;

public class StringeLife2 {
     public static String data="{\n" +
             "    \"data\":[\n" +
             "        {\n" +
             "            \"viewid\":\"logo\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"logo_top.png\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtOut\",\n" +
             "                \"width\":470,\n" +
             "                \"height\":45,\n" +
             "                \"x\":120,\n" +
             "                \"y\":80\n" +
             "            }\n" +
             "        },\n" +
             "   \n" +
             "        {\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"jiguanfengcai.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"机关风采\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":120,\n" +
             "                \"y\":194,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },\n" +
             "   \n" +
             "        {\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"minbanchuangkou.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"民办窗口\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":120,\n" +
             "                \"y\":440,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },\n" +
             "   \n" +
             "        {\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"bianminyiliao.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"便民医疗\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":120,\n" +
             "                \"y\":686,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },\n" +
             "   \n" +
             "        {\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"shiyejiaofei.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"公共事业缴费\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":460,\n" +
             "                \"y\":686,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },\n" +
             "        {\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"jiadianweixiu.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"家电维修\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":800,\n" +
             "                \"y\":686,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },{\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"fuwuzhinan.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"社会保障服务指南\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":1140,\n" +
             "                \"y\":686,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },\n" +
             "        {\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"ditu.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"地图\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":1000,\n" +
             "                \"height\":472,\n" +
             "                \"x\":460,\n" +
             "                \"y\":194,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":false\n" +
             "            }\n" +
             "        },{\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"opennews\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"mingxingqiye.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"明星企业\",\n" +
             "                \"interface\":\"FEIMWWGNPVQIRTLY\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":1480,\n" +
             "                \"y\":194,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },{\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"opennews\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"meilixiangzhen.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"魅力乡镇\",\n" +
             "                \"interface\":\"PEVANLUYDZYCFJCD\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":1480,\n" +
             "                \"y\":440,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },{\n" +
             "            \"viewid\":\"image\",\n" +
             "            \"target\":\"openvisualization\",\n" +
             "            \"content\":{\n" +
             "                \"img\":\"zhibojian.png\",\n" +
             "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
             "                \"title\":\"生活直播间\",\n" +
             "                \"interface\":\"\",\n" +
             "                \"weburl\":\"网页地址\",\n" +
             "                \"packname\":\"com.shadt.demo\",\n" +
             "                \"activity\":\"com.shadt.MainActivity\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"ImgTxtIn\",\n" +
             "                 \"width\":320,\n" +
             "                \"height\":226,\n" +
             "                \"x\":1480,\n" +
             "                \"y\":686,\n" +
             "                \"istop\":true,\n" +
             "                \"fontsize\":28,\n" +
             "                \"fontcolor\":\"#fff000\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        },\n" +
             "        \n" +
             "       {\n" +
             "            \"viewid\":\"scrolltext\",\n" +
             "             \n" +
             "            \"content\":{\n" +
             "                \"title\":\"欢迎来到可视化平台\"\n" +
             "                 \n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"leftright\",\n" +
             "                \"width\":1920,\n" +
             "                \"height\":45,\n" +
             "                \"x\":0,\n" +
             "                \"y\":970,\n" +
             "\"fontsize\":36,\n" +
             "\"fontcolor\":\"#ffffff\"\n" +
             "              \n" +
             "            }\n" +
             "        }, {\n" +
             "            \"viewid\":\"text\",\n" +
             "            \"content\":{\n" +
             "                \"title\":\"生活服务\"\n" +
             "            },\n" +
             "            \"style\":{\n" +
             "                \"mould\":\"right\",\n" +
             "                \"width\":200,\n" +
             "                \"height\":120,\n" +
             "                \"x\":1600,\n" +
             "                \"y\":45,\n" +
             "                \"fontsize\":36,\n" +
             "                \"fontcolor\":\"#ffffff\",\n" +
             "                \"bgcolor\":\"#ffffffff\",\n" +
             "                \"showtitle\":true\n" +
             "            }\n" +
             "        }\n" +
             "    ],\n" +
             "    \"code\":200,\n" +
             "    \"msg\":\"请求成功\"\n" +
             "}";
}
