package com.shadt.iptv_qx.utils;

public class Strings {
    public static String data="{\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"viewid\":\"news\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"11\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"新闻联播\",\n" +
            "                \"interface\":\"ECEPXIBQUORZSAET\",\n" +
            "                \"pageNum\":2,\n" +
            "                \"getSize\":10,\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"listSmImgL\",\n" +
            "                \"width\":480,\n" +
            "                \"height\":720,\n" +
            "                \"x\":120,\n" +
            "                \"y\":120,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#ffffff\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"refreshtime\":5000,\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"banner\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"11\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"轮播图新闻\",\n" +
            "                \"interface\":\"QOCUYAMTYITFKDVN\",\n" +
            "                \"pageNum\":1,\n" +
            "                \"getSize\":10,\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"swipeScroll\",\n" +
            "                \"width\":780,\n" +
            "                \"height\":450,\n" +
            "                \"x\":620,\n" +
            "                \"y\":120,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"refreshtime\":5000,\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"houma1.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"侯马旅游\",\n" +
            "                \"interface\":\"CMPGZGFNELGXOWHR\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":450,\n" +
            "                \"x\":1420,\n" +
            "                \"y\":120,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"image1.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"疫情防控\",\n" +
            "                \"interface\":\"DADAIOGQUCVVDDYO\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":250,\n" +
            "                \"x\":620,\n" +
            "                \"y\":590,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"travel.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"游山西读历史\",\n" +
            "                \"interface\":\"RARPIJAEHSAIDTQV\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":250,\n" +
            "                \"x\":1020,\n" +
            "                \"y\":590,\n" +
            "                \"istop\":true,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },\n" +
            "        {\n" +
            "            \"viewid\":\"image\",\n" +
            "            \"target\":\"opennews\",\n" +
            "            \"content\":{\n" +
            "                \"img\":\"icon_fupin.png\",\n" +
            "                \"backgroundimg\":\"点击页面图片背景，没有就是默认\",\n" +
            "                \"title\":\"脱贫攻坚\",\n" +
            "                \"interface\":\"EPHLMYVHYCSCAQVP\",\n" +
            "                \"weburl\":\"网页地址\",\n" +
            "                \"packname\":\"com.shadt.demo\",\n" +
            "                \"activity\":\"com.shadt.MainActivity\"\n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtIn\",\n" +
            "                \"width\":380,\n" +
            "                \"height\":250,\n" +
            "                \"x\":1420,\n" +
            "                \"y\":590,\n" +
            "                \"istop\":false,\n" +
            "                \"fontsize\":28,\n" +
            "                \"fontcolor\":\"#fff000\",\n" +
            "                \"bgcolor\":\"#ffffffff\",\n" +
            "                \"showtitle\":true\n" +
            "            }\n" +
            "        },{\n" +
            "            \"viewid\":\"logo\",\n" +
            "             \n" +
            "            \"content\":{\n" +
            "                \"img\":\"logo_top.png\"\n" +
            "                 \n" +
            "            },\n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtOut\",\n" +
            "                \"width\":470,\n" +
            "                \"height\":45,\n" +
            "                \"x\":120,\n" +
            "                \"y\":30\n" +
            "              \n" +
            "            }\n" +
            "        },{\n" +
            "            \"viewid\":\"time\",\n" +
            "          \n" +
            "            \"style\":{\n" +
            "                \"mould\":\"ImgTxtOut\",\n" +
            "                \"width\":400,\n" +
            "                \"height\":120,\n" +
            "                \"x\":1450,\n" +
            "                \"y\":40\n" +
            "               \n" +
            "            }\n" +
            "        }\n" +
            "    ],\n" +
            "    \"code\":200,\n" +
            "    \"msg\":\"请求成功\"\n" +
            "}";


}
