package com.shadt.iptv_qx.utils;

public class Test {
    public static String s="[\n" +
            "    {\n" +
            "        \"type\":\"time\",\n" +
            "        \"mould\":\"yyyy-MM-dd\",\n" +
            "        \"abscissa\":1620,\n" +
            "        \"ordinate\":0,\n" +
            "        \"width\":300,\n" +
            "        \"height\":70,\n" +
            "        \"targetType\":\"openvisualization\",\n" +
            "        \"target\":\"\",\n" +
            "        \"color\":\"#fff\",\n" +
            "        \"fontSize\":24,\n" +
            "        \"backgroundColor\":\"\",\n" +
            "        \"backgroundImage\":\"\",\n" +
            "        \"borderSize\":0,\n" +
            "        \"borderRadius\":0,\n" +
            "        \"borderColor\":\"#000000\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"type\":\"logo\",\n" +
            "        \"imgSrc\":\"http://192.168.0.88:8080/img/uploadFiles/2020-12-14/c2624bf7a25b41e3bf6af5f7fb4b395e.jpg\",\n" +
            "        \"abscissa\":0,\n" +
            "        \"ordinate\":0,\n" +
            "        \"width\":160,\n" +
            "        \"height\":134,\n" +
            "        \"targetType\":\"openvisualization\",\n" +
            "        \"target\":\"\",\n" +
            "        \"color\":\"#fff\",\n" +
            "        \"fontSize\":24,\n" +
            "        \"backgroundColor\":\"\",\n" +
            "        \"backgroundImage\":\"\",\n" +
            "        \"borderSize\":0,\n" +
            "        \"borderRadius\":0,\n" +
            "        \"borderColor\":\"#000000\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"type\":\"notice\",\n" +
            "        \"sourceType\":\"interface\",\n" +
            "        \"interface\":\"http://192.168.2.15:7090/Record/listRecordByseq?seq=210&amp;recordCount=5\",\n" +
            "        \"sourceKey\":\"\",\n" +
            "        \"sourceNum\":\"1\",\n" +
            "        \"listData\":[\n" +
            "            {\n" +
            "                \"createtime\":\"2020-01-12T05:53:43.000+0000\",\n" +
            "                \"channelseq\":210,\n" +
            "                \"isno\":\"11129374\",\n" +
            "                \"updatetime\":\"2020-01-12T05:53:43.000+0000\",\n" +
            "                \"title\":\"邹平看点1\",\n" +
            "                \"platForm\":\"xinwenzixun\",\n" +
            "                \"seq\":11129374,\n" +
            "                \"uniqueID\":\"374e1067-a99b-4798-9ae0-63a9b56d67e2\",\n" +
            "                \"dataCrosshead\":\"测试标题图\",\n" +
            "                \"RecordJumpUrl\":\"-897424\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"createtime\":\"2019-05-08T06:38:47.000+0000\",\n" +
            "                \"channelseq\":210,\n" +
            "                \"isno\":\"11127888\",\n" +
            "                \"updatetime\":\"2019-05-08T06:38:47.000+0000\",\n" +
            "                \"title\":\"邹平看点1\",\n" +
            "                \"platForm\":\"xinwenzixun\",\n" +
            "                \"seq\":11127888,\n" +
            "                \"uniqueID\":\"d7eff3a5-995e-4306-8fd3-048b79332b39\",\n" +
            "                \"dataCrosshead\":\"\"\n" +
            "            }\n" +
            "        ],\n" +
            "        \"gap\":10,\n" +
            "        \"rate\":5000,\n" +
            "        \"abscissa\":0,\n" +
            "        \"ordinate\":1020,\n" +
            "        \"width\":1920,\n" +
            "        \"height\":60,\n" +
            "        \"targetType\":\"openvisualization\",\n" +
            "        \"target\":\"\",\n" +
            "        \"color\":\"#fff\",\n" +
            "        \"fontSize\":24,\n" +
            "        \"backgroundColor\":\"\",\n" +
            "        \"backgroundImage\":\"\",\n" +
            "        \"borderSize\":0,\n" +
            "        \"borderRadius\":0,\n" +
            "        \"borderColor\":\"#000000\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"type\":\"navigation\",\n" +
            "        \"sourceType\":\"interface\",\n" +
            "        \"navData\":[\n" +
            "            {\n" +
            "                \"id\":\"415\",\n" +
            "                \"title\":\"首页\",\n" +
            "                \"icon\":{\n" +
            "                    \"value\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACZ0lEQVRIS+VWQXLaMBR939RyuwrdBbKAniBwgsIJSk6Q6Q2SDZ6sQlaps0l6gtIThJ6A9ARpTwAsGmdXumqRB//MVyxG9pgMNNNVtWIkoff1/ntPJvzjQc85v3nJ1T86eUeEauD7n6fHNC+elwOoRfqIQTvFTRXiLz/66ps7v3ehWyljDKCazc89Qre4bwVQi/QNgLcAvhYAmgAanFL3/sSXPXAOnwXK78jcQiey1iiCGIDd86RDHo89QrtYgaxn4IhD1SkebmkRuspADEA9WgwYdBqHqrQndj1Q/uuFTiYATOVFzh2QnUD5bVnfCoDABwy6FqCyhkqxGchPS+lWAEx4T4xPTwHsnv9ukleZSDF3YTDaCkAorEVapDgJlN9dQ5Eo602g/KZLUU+uvrbJF8kIzFWnyaKYHEhGjTncI3SsWFyZis4bIOT0DjY6b9krOzI1IJwuD2SOvMp18XAzbzVvKlgkAxBaOR8QzYnTofBZYjQBscaceYTeWqP9TWRIUVprYzSl1M2TUfHY/ReXILbWdzFHcV99tBPGmBU+LSuKl3RmHb+iKGvQrVBG4GH+j9Rk4BDAcRyqK+t6iRQCm+iwg0Fym303LqxMjYrW6bse6SED+3Go2tnvVhyqfK8ylFqkp1LkXRgMVjfYNCoyH5iqRbJlFEluyc3+T4CjOFRVN7o3pijL+FvXrTkD6mQMolnc93u1D/oKhENOl+37k1fTEvNJXJyJ4nJOztQhciwbv2y+ZJJ+jJXy8d19K3IPTD1a9CR3Ctqec7ocudWaxz5Jeh6zPKerkRJNX/r+yHX0s74qNomXBwGbuiiurcvIAAAAAElFTkSuQmCC\"\n" +
            "                }\n" +
            "            },\n" +
            "            {\n" +
            "                \"id\":\"418\",\n" +
            "                \"title\":\"新时代文明实践\",\n" +
            "                \"icon\":{\n" +
            "                    \"value\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACZ0lEQVRIS+VWQXLaMBR939RyuwrdBbKAniBwgsIJSk6Q6Q2SDZ6sQlaps0l6gtIThJ6A9ARpTwAsGmdXumqRB//MVyxG9pgMNNNVtWIkoff1/ntPJvzjQc85v3nJ1T86eUeEauD7n6fHNC+elwOoRfqIQTvFTRXiLz/66ps7v3ehWyljDKCazc89Qre4bwVQi/QNgLcAvhYAmgAanFL3/sSXPXAOnwXK78jcQiey1iiCGIDd86RDHo89QrtYgaxn4IhD1SkebmkRuspADEA9WgwYdBqHqrQndj1Q/uuFTiYATOVFzh2QnUD5bVnfCoDABwy6FqCyhkqxGchPS+lWAEx4T4xPTwHsnv9ukleZSDF3YTDaCkAorEVapDgJlN9dQ5Eo602g/KZLUU+uvrbJF8kIzFWnyaKYHEhGjTncI3SsWFyZis4bIOT0DjY6b9krOzI1IJwuD2SOvMp18XAzbzVvKlgkAxBaOR8QzYnTofBZYjQBscaceYTeWqP9TWRIUVprYzSl1M2TUfHY/ReXILbWdzFHcV99tBPGmBU+LSuKl3RmHb+iKGvQrVBG4GH+j9Rk4BDAcRyqK+t6iRQCm+iwg0Fym303LqxMjYrW6bse6SED+3Go2tnvVhyqfK8ylFqkp1LkXRgMVjfYNCoyH5iqRbJlFEluyc3+T4CjOFRVN7o3pijL+FvXrTkD6mQMolnc93u1D/oKhENOl+37k1fTEvNJXJyJ4nJOztQhciwbv2y+ZJJ+jJXy8d19K3IPTD1a9CR3Ctqec7ocudWaxz5Jeh6zPKerkRJNX/r+yHX0s74qNomXBwGbuiiurcvIAAAAAElFTkSuQmCC\"\n" +
            "                }\n" +
            "            },\n" +
            "            {\n" +
            "                \"id\":\"420\",\n" +
            "                \"title\":\"党建专区\",\n" +
            "                \"icon\":{\n" +
            "                    \"value\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACZ0lEQVRIS+VWQXLaMBR939RyuwrdBbKAniBwgsIJSk6Q6Q2SDZ6sQlaps0l6gtIThJ6A9ARpTwAsGmdXumqRB//MVyxG9pgMNNNVtWIkoff1/ntPJvzjQc85v3nJ1T86eUeEauD7n6fHNC+elwOoRfqIQTvFTRXiLz/66ps7v3ehWyljDKCazc89Qre4bwVQi/QNgLcAvhYAmgAanFL3/sSXPXAOnwXK78jcQiey1iiCGIDd86RDHo89QrtYgaxn4IhD1SkebmkRuspADEA9WgwYdBqHqrQndj1Q/uuFTiYATOVFzh2QnUD5bVnfCoDABwy6FqCyhkqxGchPS+lWAEx4T4xPTwHsnv9ukleZSDF3YTDaCkAorEVapDgJlN9dQ5Eo602g/KZLUU+uvrbJF8kIzFWnyaKYHEhGjTncI3SsWFyZis4bIOT0DjY6b9krOzI1IJwuD2SOvMp18XAzbzVvKlgkAxBaOR8QzYnTofBZYjQBscaceYTeWqP9TWRIUVprYzSl1M2TUfHY/ReXILbWdzFHcV99tBPGmBU+LSuKl3RmHb+iKGvQrVBG4GH+j9Rk4BDAcRyqK+t6iRQCm+iwg0Fym303LqxMjYrW6bse6SED+3Go2tnvVhyqfK8ylFqkp1LkXRgMVjfYNCoyH5iqRbJlFEluyc3+T4CjOFRVN7o3pijL+FvXrTkD6mQMolnc93u1D/oKhENOl+37k1fTEvNJXJyJ4nJOztQhciwbv2y+ZJJ+jJXy8d19K3IPTD1a9CR3Ctqec7ocudWaxz5Jeh6zPKerkRJNX/r+yHX0s74qNomXBwGbuiiurcvIAAAAAElFTkSuQmCC\"\n" +
            "                }\n" +
            "            },\n" +
            "            {\n" +
            "                \"id\":\"444\",\n" +
            "                \"title\":\"清华大学出版社\",\n" +
            "                \"icon\":{\n" +
            "                    \"value\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACZ0lEQVRIS+VWQXLaMBR939RyuwrdBbKAniBwgsIJSk6Q6Q2SDZ6sQlaps0l6gtIThJ6A9ARpTwAsGmdXumqRB//MVyxG9pgMNNNVtWIkoff1/ntPJvzjQc85v3nJ1T86eUeEauD7n6fHNC+elwOoRfqIQTvFTRXiLz/66ps7v3ehWyljDKCazc89Qre4bwVQi/QNgLcAvhYAmgAanFL3/sSXPXAOnwXK78jcQiey1iiCGIDd86RDHo89QrtYgaxn4IhD1SkebmkRuspADEA9WgwYdBqHqrQndj1Q/uuFTiYATOVFzh2QnUD5bVnfCoDABwy6FqCyhkqxGchPS+lWAEx4T4xPTwHsnv9ukleZSDF3YTDaCkAorEVapDgJlN9dQ5Eo602g/KZLUU+uvrbJF8kIzFWnyaKYHEhGjTncI3SsWFyZis4bIOT0DjY6b9krOzI1IJwuD2SOvMp18XAzbzVvKlgkAxBaOR8QzYnTofBZYjQBscaceYTeWqP9TWRIUVprYzSl1M2TUfHY/ReXILbWdzFHcV99tBPGmBU+LSuKl3RmHb+iKGvQrVBG4GH+j9Rk4BDAcRyqK+t6iRQCm+iwg0Fym303LqxMjYrW6bse6SED+3Go2tnvVhyqfK8ylFqkp1LkXRgMVjfYNCoyH5iqRbJlFEluyc3+T4CjOFRVN7o3pijL+FvXrTkD6mQMolnc93u1D/oKhENOl+37k1fTEvNJXJyJ4nJOztQhciwbv2y+ZJJ+jJXy8d19K3IPTD1a9CR3Ctqec7ocudWaxz5Jeh6zPKerkRJNX/r+yHX0s74qNomXBwGbuiiurcvIAAAAAElFTkSuQmCC\"\n" +
            "                }\n" +
            "            },\n" +
            "            {\n" +
            "                \"id\":\"447\",\n" +
            "                \"title\":\"建国事迹\",\n" +
            "                \"icon\":{\n" +
            "                    \"value\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACZ0lEQVRIS+VWQXLaMBR939RyuwrdBbKAniBwgsIJSk6Q6Q2SDZ6sQlaps0l6gtIThJ6A9ARpTwAsGmdXumqRB//MVyxG9pgMNNNVtWIkoff1/ntPJvzjQc85v3nJ1T86eUeEauD7n6fHNC+elwOoRfqIQTvFTRXiLz/66ps7v3ehWyljDKCazc89Qre4bwVQi/QNgLcAvhYAmgAanFL3/sSXPXAOnwXK78jcQiey1iiCGIDd86RDHo89QrtYgaxn4IhD1SkebmkRuspADEA9WgwYdBqHqrQndj1Q/uuFTiYATOVFzh2QnUD5bVnfCoDABwy6FqCyhkqxGchPS+lWAEx4T4xPTwHsnv9ukleZSDF3YTDaCkAorEVapDgJlN9dQ5Eo602g/KZLUU+uvrbJF8kIzFWnyaKYHEhGjTncI3SsWFyZis4bIOT0DjY6b9krOzI1IJwuD2SOvMp18XAzbzVvKlgkAxBaOR8QzYnTofBZYjQBscaceYTeWqP9TWRIUVprYzSl1M2TUfHY/ReXILbWdzFHcV99tBPGmBU+LSuKl3RmHb+iKGvQrVBG4GH+j9Rk4BDAcRyqK+t6iRQCm+iwg0Fym303LqxMjYrW6bse6SED+3Go2tnvVhyqfK8ylFqkp1LkXRgMVjfYNCoyH5iqRbJlFEluyc3+T4CjOFRVN7o3pijL+FvXrTkD6mQMolnc93u1D/oKhENOl+37k1fTEvNJXJyJ4nJOztQhciwbv2y+ZJJ+jJXy8d19K3IPTD1a9CR3Ctqec7ocudWaxz5Jeh6zPKerkRJNX/r+yHX0s74qNomXBwGbuiiurcvIAAAAAElFTkSuQmCC\"\n" +
            "                }\n" +
            "            }\n" +
            "        ],\n" +
            "        \"gap\":10,\n" +
            "        \"istop\":0,\n" +
            "        \"abscissa\":160,\n" +
            "        \"ordinate\":70,\n" +
            "        \"width\":1600,\n" +
            "        \"height\":60,\n" +
            "        \"targetType\":\"openvisualization\",\n" +
            "        \"target\":\"\",\n" +
            "        \"color\":\"#fff\",\n" +
            "        \"fontSize\":24,\n" +
            "        \"backgroundColor\":\"\",\n" +
            "        \"backgroundImage\":\"\",\n" +
            "        \"borderSize\":0,\n" +
            "        \"borderRadius\":0,\n" +
            "        \"borderColor\":\"#000000\"\n" +
            "    }\n" +
            "]";
}
